language: java

jdk:
- openjdk14

before_install:
 - chmod +x gradlew

services:
 - postgresql

before_script:
 - psql -c 'create database users;' -U postgres

script:
 - ./gradlew task travis update
 - ./gradlew build